# Generated by Django 3.2 on 2021-05-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='date_doanted',
            new_name='date_donated',
        ),
    ]
