# Generated by Django 3.2 on 2021-05-07 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_date_doanted_donation_date_donated'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.charity'),
        ),
    ]
