# Generated by Django 3.2 on 2021-05-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_donation_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='default_donation',
            field=models.FloatField(default=5.0),
        ),
    ]
