# Generated by Django 3.2 on 2022-03-15 10:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_alter_donation_donor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donor',
            new_name='Customer',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donated_to',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.DeleteModel(
            name='Charity',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
