# Generated by Django 3.2 on 2022-03-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='donated',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
    ]
