# Generated by Django 3.2 on 2022-03-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_room_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='image_url',
            new_name='image',
        ),
    ]
