# Generated by Django 3.2 on 2022-03-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='schedule',
            new_name='time_slot',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
