# Generated by Django 3.2 on 2022-03-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_date_reservation_reserved_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_date',
        ),
    ]
