# Generated by Django 3.2 on 2022-03-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_date_reservation_date_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_field',
            new_name='date',
        ),
    ]
