# Generated by Django 3.2 on 2022-03-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_date_field_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
